### ISSUE TITLE
“Error in x[, ind1] * x[, ind2]: non-numeric argument to binary operator”

### ISSUE THREAD

**Issue by Dingchunyuan** [kalaga27/tcrpheno#1]
hi, 

when I run this software ,there is an error that  ```Error in x[, ind1] * x[, ind2]: non-numeric argument to binary operator```，then I tried to follow the original code step by step to find how this error was generated. I found that the first step in the `score_tcrs` function is `featurize_tcrs`. The first step in the `featurize_tcrs` function seems to filter `TRBVgrid$gene`, but there is no input for the `TRBVgrid` file, not only in the `score_tcrs` function but also in the `tcrpheno_input.rda` example files. So the error becomes: ``` Error: object ‘TRBVgrid’ not found ``` I want to know ,there is something I miss? By the way ,I use bulk RNA TCR sequence rather than scTCR

##My input file
```
sample           TCRB_cdr3aa               TCRB_vgene    TCRB_jgene                                      TCRB_cdr3nt 64 
ESCC-P25-T3  CASSYTGAPGDEKLFF  TRBV6-6*01    TRBJ1-4*01    TGTGCCAGCAGTTACACAGGGGCCCCAGGGGATGAAAAACTGTTTTTT 
ESCC-P25-T3  CASSYSNPEGTEAFF    TRBV6-7*01    TRBJ1-1*01    TGTGCCAGCAGTTACTCGAACCCAGAGGGCACTGAAGCTTTCTTT 
ESCC-P25-T3  CASRTVGTEAFF           TRBV19*01     TRBJ1-1*01    TGTGCCAGTAGGACAGTGGGCACTGAAGCTTTCTTT 
```

thanks

**Comment by leeanapeters** [comment]
Hi, I am having the same issue using bulk TCRB data. @Dingchunyuan @kalaga27 were you able to resolve this?

My issue seems to arise at the "adding interactions between adjacent residues" step

 traceback()
3: add_adjacent_ints(res, "TRBcdr3_p")
2: featurize_tcrs(data, chain)
1: score_tcrs(input, chain = "b")


My data looks similar to the above

            id     TCRB_cdr3aa       TCRB_vgene TCRB_jgene
1 HDL003_SPL_TCRB CASSQWTGFSYEQYF       TCRBV04-02 TCRBJ02-07
2 HDL003_SPL_TCRB    CASSLGFYGYTF TCRBV12-03/12-04 TCRBJ01-02
3 HDL003_SPL_TCRB   CASSLVRYYGYTF       TCRBV11-02 TCRBJ01-02
4 HDL003_SPL_TCRB  CASSLGQLNYGYTF TCRBV03-01/03-02 TCRBJ01-02
5 HDL003_SPL_TCRB                       TCRBV19-01 TCRBJ01-02
6 HDL003_SPL_TCRB   CASRGHSGNTIYF       TCRBV10-01 TCRBJ01-03
                                                                              TCRB_cdr3nt
1 CACACCCTGCAGCCAGAAGACTCGGCCCTGTATCTCTGTGCCAGCAGCCAGTGGACAGGCTTTTCCTACGAGCAGTACTTCGGGCCG
2 NTGAAGATCCAGCCCTCAGAACCCAGGGACTCAGCTGTGTACTTCTGTGCCAGCAGTTTAGGGTTTTATGGCTACACCTTCGGTTCG
3 AAGATCCAGCCTGCAAAGCTTGAGGACTCGGCCGTGTATCTCTGTGCCAGCAGCTTAGTTCGGTACTATGGCTACACCTTCGGTTCG
4 ATCAATTCCCTGGAGCTTGGTGACTCTGCTGTGTATTTCTGTGCCAGCAGCCTGGGACAGCTTAACTATGGCTACACCTTCGGTTCG
5 CTGTGACATCGGCCCAAAAGAACCCGACAGCTTTCTATCTCTGTGCCAGTAGTACCGACAGGAGACTATGGCTACACCTTCGGTTCG
6 ACTCTGTAGTCTGCTGCCTCCTCCCAGACATCTGTATATTTCTGCGCCAGCAGGGGACACTCTGGAAACACCATATATTTTGGAGAG

**Comment by kalaga27** [comment]
Hi @leeanapeters and @Dingchunyuan, thank you for bringing this to my attention.  Can you let me know what version of R you are using, and what command you used to install tcrpheno?

**Comment by Dingchunyuan** [comment]
> Hi, I am having the same issue using bulk TCRB data. [@Dingchunyuan](https://github.com/Dingchunyuan) [@kalaga27](https://github.com/kalaga27) were you able to resolve this?
> 
> My issue seems to arise at the "adding interactions between adjacent residues" step
> 
> traceback() 3: add_adjacent_ints(res, "TRBcdr3_p") 2: featurize_tcrs(data, chain) 1: score_tcrs(input, chain = "b")
> 
> My data looks similar to the above
> 
> ```
>         id     TCRB_cdr3aa       TCRB_vgene TCRB_jgene
> ```
> 
> 1 HDL003_SPL_TCRB CASSQWTGFSYEQYF TCRBV04-02 TCRBJ02-07 2 HDL003_SPL_TCRB CASSLGFYGYTF TCRBV12-03/12-04 TCRBJ01-02 3 HDL003_SPL_TCRB CASSLVRYYGYTF TCRBV11-02 TCRBJ01-02 4 HDL003_SPL_TCRB CASSLGQLNYGYTF TCRBV03-01/03-02 TCRBJ01-02 5 HDL003_SPL_TCRB TCRBV19-01 TCRBJ01-02 6 HDL003_SPL_TCRB CASRGHSGNTIYF TCRBV10-01 TCRBJ01-03 TCRB_cdr3nt 1 CACACCCTGCAGCCAGAAGACTCGGCCCTGTATCTCTGTGCCAGCAGCCAGTGGACAGGCTTTTCCTACGAGCAGTACTTCGGGCCG 2 NTGAAGATCCAGCCCTCAGAACCCAGGGACTCAGCTGTGTACTTCTGTGCCAGCAGTTTAGGGTTTTATGGCTACACCTTCGGTTCG 3 AAGATCCAGCCTGCAAAGCTTGAGGACTCGGCCGTGTATCTCTGTGCCAGCAGCTTAGTTCGGTACTATGGCTACACCTTCGGTTCG 4 ATCAATTCCCTGGAGCTTGGTGACTCTGCTGTGTATTTCTGTGCCAGCAGCCTGGGACAGCTTAACTATGGCTACACCTTCGGTTCG 5 CTGTGACATCGGCCCAAAAGAACCCGACAGCTTTCTATCTCTGTGCCAGTAGTACCGACAGGAGACTATGGCTACACCTTCGGTTCG 6 ACTCTGTAGTCTGCTGCCTCCTCCCAGACATCTGTATATTTCTGCGCCAGCAGGGGACACTCTGGAAACACCATATATTTTGGAGAG

hi，I fixed this by loading ‘sysdata.rda’ in my working directory. maybe you can have a try.

**Comment by leeanapeters** [comment]
Hi @Dingchunyuan, I tried this and it didn't work for me unfortunately. 

@kalaga27, my version of R is 4.2.3

I installed tcrpheno with remotes::install_github("kalaga27/tcrpheno")

Is there a possibility that formatting differences can cause these errors? My first run was with the immunoseq format above. My second attempt I changed the TCR format to match the example rda file.

head(input1)
               id     TCRB_cdr3aa    TCRB_vgene TCRB_jgene
1 HDL003_SPL_TCRB CASSQWTGFSYEQYF       TRBV4-2    TRBJ2-7
2 HDL003_SPL_TCRB    CASSLGFYGYTF TRBV12-3/12-4    TRBJ1-2
3 HDL003_SPL_TCRB   CASSLVRYYGYTF      TRBV11-2    TRBJ1-2
4 HDL003_SPL_TCRB  CASSLGQLNYGYTF   TRBV3-1/3-2    TRBJ1-2
6 HDL003_SPL_TCRB   CASRGHSGNTIYF      TRBV10-1    TRBJ1-3
7 HDL003_SPL_TCRB CASSHRGSSGNTIYF   TRBV3-1/3-2    TRBJ1-3
                                                                              TCRB_cdr3nt
1 CACACCCTGCAGCCAGAAGACTCGGCCCTGTATCTCTGTGCCAGCAGCCAGTGGACAGGCTTTTCCTACGAGCAGTACTTCGGGCCG
2 NTGAAGATCCAGCCCTCAGAACCCAGGGACTCAGCTGTGTACTTCTGTGCCAGCAGTTTAGGGTTTTATGGCTACACCTTCGGTTCG
3 AAGATCCAGCCTGCAAAGCTTGAGGACTCGGCCGTGTATCTCTGTGCCAGCAGCTTAGTTCGGTACTATGGCTACACCTTCGGTTCG
4 ATCAATTCCCTGGAGCTTGGTGACTCTGCTGTGTATTTCTGTGCCAGCAGCCTGGGACAGCTTAACTATGGCTACACCTTCGGTTCG
6 ACTCTGTAGTCTGCTGCCTCCTCCCAGACATCTGTATATTTCTGCGCCAGCAGGGGACACTCTGGAAACACCATATATTTTGGAGAG
7 AATTCCCTGGAGCTTGGTGACTCTGCTGTGTATTTCTGTGCCAGCAGCCACAGGGGGAGCTCTGGAAACACCATATATTTTGGAGAG

**Comment by leeanapeters** [comment]
@kalaga27 I am still having this issue when running the code with single chain (TCRB) data, but it works perfectly with single cell data.

Do you have any ideas for troubleshooting?

Thanks!


Leeana

**Comment by Lifupeng2001** [comment]
@kalaga27 Thank you so much for your contribution. I also tried using this package to run my own data. After converting the format to the required input, I encountered the same error.  I  changed final table to numeric types[1].

sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-conda-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS/LAPACK: /home/lifupeng/mambaforge/envs/scRepertoire/lib/libopenblasp-r0.3.29.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Shanghai
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] hash_3.0.1                  tcrpheno_0.0.0.9000        
 [3] RColorBrewer_1.1-3          stringr_1.6.0              
 [5] tictoc_1.2.1                scater_1.34.1              
 [7] scuttle_1.16.0              SingleCellExperiment_1.28.1
 [9] SummarizedExperiment_1.36.0 Biobase_2.66.0             
[11] GenomicRanges_1.58.0        GenomeInfoDb_1.42.3        
[13] IRanges_2.40.1              S4Vectors_0.44.0           
[15] BiocGenerics_0.52.0         MatrixGenerics_1.18.1      
[17] matrixStats_1.5.0           rlang_1.1.6                
[19] reshape2_1.4.4              ggpubr_0.6.1               
[21] Seurat_5.3.0                SeuratObject_5.2.0         
[23] sp_2.2-0                    data.table_1.17.8          
[25] dplyr_1.1.4                 scRepertoire_2.5.7         
[27] ggplot2_4.0.0              

loaded via a namespace (and not attached):
  [1] RcppAnnoy_0.0.22        splines_4.4.1           later_1.4.4            
  [4] pbdZMQ_0.3-14           tibble_3.3.0            polyclip_1.10-7        
  [7] fastDummies_1.7.5       lifecycle_1.0.4         rstatix_0.7.2          
 [10] globals_0.18.0          lattice_0.22-7          MASS_7.3-65            
 [13] backports_1.5.0         magrittr_2.0.4          plotly_4.11.0          
 [16] httpuv_1.6.16           sctransform_0.4.2       spam_2.11-1            
 [19] spatstat.sparse_3.1-0   reticulate_1.43.0       cowplot_1.2.0          
 [22] pbapply_1.7-4           abind_1.4-8             zlibbioc_1.52.0        
 [25] rvest_1.0.5             Rtsne_0.17              purrr_1.1.0            
 [28] ggraph_2.2.2            tweenr_2.0.3            evmix_2.12             
 [31] GenomeInfoDbData_1.2.13 ggrepel_0.9.6           irlba_2.3.5.1          
 [34] listenv_0.9.1           spatstat.utils_3.2-0    iNEXT_3.0.2            
 [37] goftest_1.2-3           MatrixModels_0.5-4      RSpectra_0.16-2        
 [40] spatstat.random_3.4-2   fitdistrplus_1.2-4      parallelly_1.45.1      
 [43] codetools_0.2-20        DelayedArray_0.32.0     xml2_1.4.0             
 [46] ggforce_0.5.0           tidyselect_1.2.1        UCSC.utils_1.2.0       
 [49] farver_2.1.2            ScaledMatrix_1.14.0     viridis_0.6.5          
 [52] base64enc_0.1-3         spatstat.explore_3.5-3  jsonlite_2.0.0         
 [55] BiocNeighbors_2.0.1     Formula_1.2-5           tidygraph_1.3.1        
 [58] progressr_0.17.0        ggridges_0.5.7          ggalluvial_0.12.5      
 [61] survival_3.8-3          systemfonts_1.3.1       tools_4.4.1            
 [64] ragg_1.5.0              ica_1.0-3               Rcpp_1.1.0             
 [67] glue_1.8.0              gridExtra_2.3           SparseArray_1.6.2      
 [70] IRdisplay_1.1           withr_3.0.2             fastmap_1.2.0          
 [73] SparseM_1.84-2          rsvd_1.0.5              digest_0.6.37          
 [76] R6_2.6.1                mime_0.13               colorspace_2.1-2       
 [79] textshaping_1.0.3       scattermore_1.2         tensor_1.5.1           
 [82] spatstat.data_3.1-9     tidyr_1.3.1             generics_0.1.4         
 [85] graphlayouts_1.2.2      httr_1.4.7              htmlwidgets_1.6.4      
 [88] S4Arrays_1.6.0          uwot_0.2.3              pkgconfig_2.0.3        
 [91] gtable_0.3.6            lmtest_0.9-40           S7_0.2.0               
 [94] XVector_0.46.0          htmltools_0.5.8.1       carData_3.0-5          
 [97] dotCall64_1.2           scales_1.4.0            png_0.1-8              
[100] spatstat.univar_3.1-4   ggdendro_0.2.0          rjson_0.2.23           
[103] uuid_1.2-1              nlme_3.1-168            repr_1.1.7             
[106] cachem_1.1.0            zoo_1.8-14              KernSmooth_2.23-26     
[109] vipor_0.4.7             parallel_4.4.1          miniUI_0.1.2           
[112] pillar_1.11.1           grid_4.4.1              vctrs_0.6.5            
[115] RANN_2.6.2              promises_1.3.3          BiocSingular_1.22.0    
[118] car_3.1-3               beachmat_2.22.0         xtable_1.8-4           
[121] cluster_2.1.8.1         beeswarm_0.4.0          evaluate_1.0.5         
[124] cli_3.6.5               compiler_4.4.1          crayon_1.5.3           
[127] ggsignif_0.6.4          future.apply_1.20.0     immApex_1.3.7          
[130] ggbeeswarm_0.7.2        plyr_1.8.9              stringi_1.8.7          
[133] BiocParallel_1.40.2     viridisLite_0.4.2       deldir_2.0-4           
[136] gsl_2.1-8               lazyeval_0.2.2          spatstat.geom_3.6-0    
[139] quantreg_6.1            Matrix_1.7-4            IRkernel_1.3.2         
[142] RcppHNSW_0.6.0          patchwork_1.3.2         future_1.67.0          
[145] shiny_1.11.1            ROCR_1.0-11             broom_1.0.10           
[148] igraph_2.2.0            memoise_2.0.1          

[1]
cdr3_cols <- grep("^(TRAcdr3_p|TRBcdr3_p)", colnames(res), value = TRUE)
res[cdr3_cols] 
res[cdr3_cols] <- lapply(res[cdr3_cols], function(x) as.numeric(as.character(x)))
>
TRAcdr3_p1_AF1<named list> | TRAcdr3_p1_AF2<named list> | TRAcdr3_p1_AF3<named list> | TRAcdr3_p1_AF4<named list> | TRAcdr3_p1_AF5<named list> | TRAcdr3_p2_AF1<named list> | TRAcdr3_p2_AF2<named list> | TRAcdr3_p2_AF3<named list> | TRAcdr3_p2_AF4 | TRAcdr3_p2_AF5<named list> | ⋯ | TRBcdr3_p17_AF1<dbl> | TRBcdr3_p17_AF2<dbl> | TRBcdr3_p17_AF3<dbl> | TRBcdr3_p17_AF4 <dbl>| TRBcdr3_p17_AF5 <dbl>| TRBcdr3_p18_AF1<dbl> | TRBcdr3_p18_AF2<dbl> | TRBcdr3_p18_AF3<dbl> | TRBcdr3_p18_AF4<dbl> | TRBcdr3_p18_AF5<dbl>
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | -1.006 | -0.59 | 1.891 | -0.397 | 0.412
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
-1.343 | 0.465 | -0.862 | -1.02 | -0.255 | -0.591 | -1.302 | -0.733 | 1.57 | -0.146 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | NA | NA | NA | NA | NA
-1.343 | 0.465 | -0.862 | -1.02 | -0.255 | -0.591 | -1.302 | -0.733 | 1.57 | -0.146 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | 0.260 | 0.83 | 3.097 | -0.838 | 1.512 | -1.006 | -0.59 | 1.891 | -0.397 | 0.412
-1.343 | 0.465 | -0.862 | -1.02 | -0.255 | -0.591 | -1.302 | -0.733 | 1.57 | -0.146 | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | -1.006 | -0.59 | 1.891 | -0.397 | 0.412 | -1.006 | -0.59 | 1.891 | -0.397 | 0.412
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
-1.343 | 0.465 | -0.862 | -1.02 | -0.255 | -0.591 | -1.302 | -0.733 | 1.57 | -0.146 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋱ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮ | ⋮
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | NA | NA | NA | NA | NA | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA
NA | NA | NA | NA | NA | -1.343 | 0.465 | -0.862 | -1.02 | -0.255 | ⋯ | NA | NA | NA | NA | NA | NA | NA | NA | NA | NA

<img width="1276" height="61" alt="Image" src="https://github.com/user-attachments/assets/260f18fa-1a8e-467e-8774-8ee44527a92c" />

Finally can work in my data! 
I'm wondering if this is theoretically feasible.

best wishes!
Fupeng LI

**Comment by kalaga27** [comment]
> [@kalaga27](https://github.com/kalaga27) I am still having this issue when running the code with single chain (TCRB) data, but it works perfectly with single cell data.
> 
> Do you have any ideas for troubleshooting?
> 
> Thanks!
> 
> Leeana

Hi @leeanapeters, I just re-ran `score_tcrs(data, chain="b")` with R 4.2.3 but wasn't able to reproduce your error. Here's what I would do:

1. Re-run `remotes::install_github("kalaga27/tcrpheno")`
2. Run `data("tcrpheno_clones")` and then `head(tcrpheno_clones)` to see how the example input data is formatted
3. Ensure your data format matches the example data format:
     - Column names should match. If you only have data for the TCRB chain, you can omit columns for the alpha chain (and vice versa).   
     - Data types in each column should match. You can run `str(tcrpheno_clones)`  and `str(your_input_data)` to compare.

If the issue persists, please run `saveRDS(your_input_data, "LP_inputdf.rds")` and email me at kalaga12@gmail.com with that file attached so I can fully check out the issue!
